name: Publish docker images

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish-docker-images:
    name: Build & publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Save current commit hash
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build & publish docker images to GHCR
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker buildx bake --file compose.publish.yaml --push
