name: deploy

on:
  push:
    branches: main

permissions:
  contents: read
  packages: write

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
      - run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker buildx bake --file compose.publish.yaml --push
